apiVersion: v2
name: user-management
description: A Helm chart for User Management API with PostgreSQL
version: 0.1.0
appVersion: "1.0.0"
type: application
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
