- name: Configure the Jenkins server
  hosts: jenkins
  become: true
  vars:
    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_compose_package_state: present
    docker_users:
      - ubuntu
      - jenkins
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: full

    - name: Install prerequisite package
      apt:
        name: software-properties-common
        state: present

    - name: Add deadsnakes PPA
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
        update_cache: yes

    - name: Install Python 3.9 and git
      apt:
        name: 
          - python3.9
          - python3.9-venv
          - python3.9-dev
          - git  
        state: present

    - name: Include roles for installing docker, jenkins and grype
      import_tasks: roles.yml

