- name: Configure the Jenkins server
  hosts: jenkins
  become: true
  vars:
    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_compose_package_state: present
    docker_users:
      - ubuntu
      - jenkins
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: full

    - name: Install prerequisite package
      apt:
        name: software-properties-common
        state: present

    - name: Add deadsnakes PPA
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
        update_cache: yes

    - name: Install Python 3.9 and git
      apt:
        name: 
          - python3.9
          - python3.9-venv
          - python3.9-dev
          - git  
          - unzip
        state: present

    - name: Include roles for installing docker, jenkins and grype
      import_tasks: roles.yml

    - name: Install Helm
      unarchive:
        src: https://get.helm.sh/helm-v3.17.0-linux-amd64.tar.gz
        dest: /usr/local/bin
        extra_opts: "--strip-components=1"
        owner: root
        group: root
        mode: 0755
        remote_src: true
      args:
        creates: /usr/local/bin/helm

    - name: Download AWS-CLI
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: true

    - name: Install awscli package.
      shell: /tmp/aws/install
